name = "trq-studio"
type = "javascript"
main = "dist/index.html"
compatibility_date = "2024-01-15"

[env.production]
name = "trq-studio"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.tsx", "src/**/*.ts", "src/**/*.css"]

[build.upload]
format = "service-worker"

[[routes]]
pattern = "*"
zone_name = "example.com"
